// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/mutualexclusion.proto

package mutualexclusion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId      int32                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderAddr    string                 `protobuf:"bytes,3,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_mutualexclusion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mutualexclusion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_mutualexclusion_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Request) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Request) GetSenderAddr() string {
	if x != nil {
		return x.SenderAddr
	}
	return ""
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_grpc_mutualexclusion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mutualexclusion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_grpc_mutualexclusion_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_mutualexclusion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_mutualexclusion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_mutualexclusion_proto_rawDescGZIP(), []int{2}
}

var File_grpc_mutualexclusion_proto protoreflect.FileDescriptor

const file_grpc_mutualexclusion_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/mutualexclusion.proto\x12\x0fmutualexclusion\"e\n" +
	"\aRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vsender_addr\x18\x03 \x01(\tR\n" +
	"senderAddr\"$\n" +
	"\x05Reply\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\"\a\n" +
	"\x05Empty2\x95\x01\n" +
	"\x0fMutualExclusion\x12B\n" +
	"\x0eReceiveRequest\x12\x18.mutualexclusion.Request\x1a\x16.mutualexclusion.Empty\x12>\n" +
	"\fReceiveReply\x12\x16.mutualexclusion.Reply\x1a\x16.mutualexclusion.EmptyB<Z:github.com/Gustav2620/Ricart-Argawala/grpc;mutualexclusionb\x06proto3"

var (
	file_grpc_mutualexclusion_proto_rawDescOnce sync.Once
	file_grpc_mutualexclusion_proto_rawDescData []byte
)

func file_grpc_mutualexclusion_proto_rawDescGZIP() []byte {
	file_grpc_mutualexclusion_proto_rawDescOnce.Do(func() {
		file_grpc_mutualexclusion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_mutualexclusion_proto_rawDesc), len(file_grpc_mutualexclusion_proto_rawDesc)))
	})
	return file_grpc_mutualexclusion_proto_rawDescData
}

var file_grpc_mutualexclusion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_mutualexclusion_proto_goTypes = []any{
	(*Request)(nil), // 0: mutualexclusion.Request
	(*Reply)(nil),   // 1: mutualexclusion.Reply
	(*Empty)(nil),   // 2: mutualexclusion.Empty
}
var file_grpc_mutualexclusion_proto_depIdxs = []int32{
	0, // 0: mutualexclusion.MutualExclusion.ReceiveRequest:input_type -> mutualexclusion.Request
	1, // 1: mutualexclusion.MutualExclusion.ReceiveReply:input_type -> mutualexclusion.Reply
	2, // 2: mutualexclusion.MutualExclusion.ReceiveRequest:output_type -> mutualexclusion.Empty
	2, // 3: mutualexclusion.MutualExclusion.ReceiveReply:output_type -> mutualexclusion.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_mutualexclusion_proto_init() }
func file_grpc_mutualexclusion_proto_init() {
	if File_grpc_mutualexclusion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_mutualexclusion_proto_rawDesc), len(file_grpc_mutualexclusion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_mutualexclusion_proto_goTypes,
		DependencyIndexes: file_grpc_mutualexclusion_proto_depIdxs,
		MessageInfos:      file_grpc_mutualexclusion_proto_msgTypes,
	}.Build()
	File_grpc_mutualexclusion_proto = out.File
	file_grpc_mutualexclusion_proto_goTypes = nil
	file_grpc_mutualexclusion_proto_depIdxs = nil
}
